version: "3.3"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  django:
    build: .
    command: ./start-django.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres

