# Generated by Django 4.0.3 on 2022-03-06 14:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoShip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('max_idle_time', models.TimeField()),
                ('max_containers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('max_items', models.IntegerField()),
                ('cargo_ship_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='dire_docks.cargoship')),
            ],
        ),
        migrations.CreateModel(
            name='Dock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('max_ships', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('AUTOMOBILES', 'Automobiles'), ('PRODUCE', 'Produce'), ('SEAFOOD', 'Seafood'), ('ELECTRONICS', 'Electronics')], max_length=100)),
                ('container_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='dire_docks.container')),
            ],
        ),
        migrations.AddField(
            model_name='cargoship',
            name='dock_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='dire_docks.dock'),
        ),
    ]
