# Generated by Django 4.0.3 on 2022-03-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dire_docks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoship',
            name='name',
            field=models.CharField(default='dire dock', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='container',
            name='name',
            field=models.CharField(default='container', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dock',
            name='name',
            field=models.CharField(default='dire dock', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='item', max_length=100),
            preserve_default=False,
        ),
    ]
