# Generated by Django 4.0.3 on 2022-03-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dire_docks', '0002_cargoship_name_container_name_dock_name_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargoship',
            old_name='dock_id',
            new_name='dock',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='cargo_ship_id',
            new_name='cargo_ship',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='container_id',
            new_name='container',
        ),
    ]
