# Generated by Django 4.0.3 on 2022-03-06 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dire_docks', '0004_alter_cargoship_dock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargoship',
            name='dock',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargo_ships', to='dire_docks.dock'),
        ),
    ]
