# Generated by Django 4.0.3 on 2022-03-06 19:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dire_docks', '0005_alter_cargoship_dock'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoship',
            name='depart_time',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargoship',
            name='dock_time',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CargoShipConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('conflicts', models.ManyToManyField(related_name='conflicts', to='dire_docks.cargoship')),
                ('parent_cargo_ship', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_ship_conflict', to='dire_docks.cargoship')),
            ],
        ),
    ]
