# Generated by Django 4.0.3 on 2022-03-06 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dire_docks', '0006_cargoship_depart_time_cargoship_dock_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargoshipconflict',
            name='conflicts',
        ),
        migrations.RemoveField(
            model_name='cargoshipconflict',
            name='parent_cargo_ship',
        ),
        migrations.AddField(
            model_name='cargoshipconflict',
            name='cargo_ship_a',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_ship_a_conflict', to='dire_docks.cargoship'),
        ),
        migrations.AddField(
            model_name='cargoshipconflict',
            name='cargo_ship_b',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_ship_b_conflict', to='dire_docks.cargoship'),
        ),
    ]
