# Generated by Django 4.0.3 on 2022-03-07 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dire_docks', '0007_remove_cargoshipconflict_conflicts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargoship',
            name='dock',
        ),
        migrations.AddField(
            model_name='cargoship',
            name='dock_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargo_ships', to='dire_docks.dock'),
        ),
    ]
