# Generated by Django 4.0.3 on 2022-03-07 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dire_docks', '0008_remove_cargoship_dock_cargoship_dock_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargoshipconflict',
            old_name='cargo_ship_a',
            new_name='cargo_ship_a_id',
        ),
        migrations.RenameField(
            model_name='cargoshipconflict',
            old_name='cargo_ship_b',
            new_name='cargo_ship_b_id',
        ),
    ]
