# Generated by Django 4.0.3 on 2022-03-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dire_docks', '0010_rename_dock_id_cargoship_dock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoshipconflict',
            name='type',
            field=models.CharField(default='One-Off', max_length=100),
            preserve_default=False,
        ),
    ]
