# Generated by Django 4.0.3 on 2022-03-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dire_docks', '0013_cargoship_conflicting_cargo_ships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargoship',
            name='conflicting_cargo_ships',
            field=models.ManyToManyField(default=None, to='dire_docks.cargoship'),
        ),
    ]
