# Generated by Django 4.0.3 on 2022-03-14 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dire_docks', '0014_alter_cargoship_conflicting_cargo_ships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargoship',
            name='conflicting_cargo_ships',
        ),
    ]
