# Generated by Django 4.0.3 on 2022-03-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dire_docks', '0015_remove_cargoship_conflicting_cargo_ships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargoship',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
