# Generated by Django 4.0.3 on 2022-03-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dire_docks', '0016_alter_cargoship_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoship',
            name='conflicting_cargo_ships',
            field=models.ManyToManyField(default=None, to='dire_docks.cargoship'),
        ),
    ]
